"""empty message

Revision ID: 9c3366aa4f39
Revises: 5077b2688f56
Create Date: 2025-10-14 00:06:13.801531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3366aa4f39'
down_revision = '5077b2688f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_timestamp'))

    op.drop_table('newsletter')
    # ### end Alembic commands ###
